[package]
name = "monolib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rodio = { version = "0.17.3", default-features = false }
byteorder = "1.5.0"

[lib]
name = "monolib"
crate-type = ["staticlib", "cdylib"]
