[package]
name = "monoclient"
version = "0.3.0"
edition = "2021"
license = "MIT"

[dependencies]
monolib = { path = "../monolib" }
clap = { version = "4.4.18", features = ["derive"] }
crossterm = "0.27.0"
